config/routes.rb
Rails.application.routes.draw do
  root to: 'plateau#index'

  get 'index/grid', to: 'plateau#index'
  get '/create/rover' , to: 'plateau#create'
  get '/start', to: 'plateau#start'
  get '/rovers/instructions' , to: 'plateau#set_up_rover'
  # resources :plateau

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plateau_controller.rb
class PlateauController < ApplicationController
  def index

    # Splits the string and supplies the X and Y axis so that the grid size can be made
    if params[:x_y]
      @x_axis = params[:x_y].split(" ")[0].to_i
      @y_axis = params[:x_y].split(" ")[1].to_i
    else
      @x_axis = 0
      @y_axis = 0
    end

    # Builds the string for the css grid to be used on the front-end
    @css_auto_grid = "" 
    (0..@x_axis).each do |x_axis| 
      @css_auto_grid += "auto "
    end
    
    # Sets the width of the plateau
    @width = 100 * @x_axis
    
    # Builds the array that is used to map out the grid
    @grid_hash = []
    range = @x_axis..0
    (0..@y_axis).each do |y_axis| 
      (range.first).downto(range.last).each do |x_axis| 
        @grid_hash << "#{x_axis}_#{y_axis}"
      end
    end

    # Defining globel variables that contains all the rovers information
    $rover_id = 0
    $rover = [{:id => 0, :path => nil, :facing => nil, :directions => nil, :degrees => nil , :cardinal_compass_points => nil}]
    $rotation = 0
  end

  # Creates a new rover and adds it to the array of existing rovers
  def create
    $rover_id = $rover_id.next
    $rover << {:id => $rover_id, :path => nil, :facing => nil, :directions => nil, :degrees => nil, :cardinal_compass_points => nil}
    respond_to do |format|
      format.js
    end
  end

  # Here we set the starting point and the path the rover will take
  def set_up_rover
    $rover.each_with_index do |rover,id|
      array = params["path#{id}"].split(" ")
      direction_facing = array.pop
      position = array
      start_at = "#{position[0]}_#{position[1]} "

      rover[:path] = start_at.split(" ")
      rover[:facing] = direction_facing
      rover[:directions] = params["directions#{id}"].upcase.split("")
    end
  end

  # builds the array that provides the rotation/path/cardinal compass point for each rover
  def start
    array = []
    $rover_orientation = ""
    cardinal_compass_points = []
    index = params[:pass_rover].to_i

    if $rover[index][:facing] == "N"
      $rotation = 0
      $rover[index][:degrees] = array << $rotation
      cardinal_compass_points << "North"
    elsif $rover[index][:facing] == "E"
      $rotation = 90
      $rover[index][:degrees] = array << $rotation
      cardinal_compass_points << "East"
    elsif $rover[index][:facing] == "S"
      $rotation = 180
      $rover[index][:degrees] = array << $rotation
      cardinal_compass_points << "South"
    elsif $rover[index][:facing] == "W"
      $rotation = 270
      $rover[index][:degrees] = array << $rotation
      cardinal_compass_points << "West"
    end

      $rover[index][:directions].each do |directions|
      
        if directions == "L"
          $rotation -= 90
          $rover[index][:degrees] = array << $rotation
        elsif directions == "R"
          $rotation += 90
          $rover[index][:degrees] = array << $rotation
        end
        
        if $rotation / 90 % 4 == 0
          $rover_orientation = "N"
          cardinal_compass_points << "North"
        elsif $rotation / 90 % 4 == 1
          $rover_orientation = "E"
          cardinal_compass_points << "East"
        elsif $rotation / 90 % 4 == 2 
          $rover_orientation = "S"
          cardinal_compass_points << "South"
        elsif $rotation / 90 % 4 == 3
          $rover_orientation = "W"
          cardinal_compass_points << "West"
        elsif $rotation / 90 % 4 == -1
          $rover_orientation = "W"
          cardinal_compass_points << "West"
        elsif $rotation / 90 % 4 == -2
          $rover_orientation = "S"
          cardinal_compass_points << "South"
        elsif $rotation / 90 % 4 == -3
          $rover_orientation = "E"
          cardinal_compass_points << "East"
        end

        if directions == "M" && $rover_orientation == "N"
          # just increases the value on the y-axis
          $rover[index][:degrees] = array << "M"
          $rover[index][:path] << "#{$rover[index][:path].last.split("_")[0].to_i}_#{$rover[index][:path].last.split("_")[1].to_i + 1}"
        elsif directions == "M" && $rover_orientation == "E"
          # just increases the value on the x-axis
          $rover[index][:degrees] = array << "M"
          $rover[index][:path] << "#{$rover[index][:path].last.split("_")[0].to_i + 1}_#{$rover[index][:path].last.split("_")[1].to_i}"
        elsif directions == "M" && $rover_orientation == "S"
          # just decreases the value on the y-axis
          $rover[index][:degrees] = array << "M"
          $rover[index][:path] << "#{$rover[index][:path].last.split("_")[0].to_i}_#{$rover[index][:path].last.split("_")[1].to_i - 1}"
        elsif directions == "M" && $rover_orientation == "W"  
          # just decreases the value on the x-axis
          $rover[index][:degrees] = array << "M"
          $rover[index][:path] << "#{$rover[index][:path].last.split("_")[0].to_i - 1}_#{$rover[index][:path].last.split("_")[1].to_i}"
        end
        
      end
      
    $rover[index][:cardinal_compass_points] = cardinal_compass_points
    
     @rover_array_of_hashes = $rover
    respond_to do |format|
      format.json {render json: @rover_array_of_hashes[params[:pass_rover].to_i]}
    end
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plateau_helper.rb
module PlateauHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarsRoverChallengeInRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style>

      html{
        background-color:#333;
      }

      /* creates the individual x,y locations for the plateau */
      .location{
        background-color: rgba(255, 255, 255, 0.8);
        border: 1px solid rgba(0, 0, 0, 0.8);
        padding: 5px;
        font-size: 12px;
        text-align: center;
        height: 100px;
        width: 100px;
      }

      /* creates the grid frontend layout */
      .plateau_panel{
        display: grid;
        grid-template-columns: <%= @css_auto_grid %>;
        padding: 10px;
        width:<%= "#{@width}px" %>;
      }

      #log{
        background-color: black;
        padding: 12px;
        height: 150px;
        color: lawngreen;
        overflow: scroll;
      }
    
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/plateau/index.html.erb
<div class="input_panel">
    <div>
    <%# Here you set the grid size using the X and Y axis %>
        <%= form_tag(root_path, method: :get) do %>
        <label>Set grid size:</label> 
             <%= text_field_tag :x_y, params[:x_y], autocomplete: 'off' %>
            <%= submit_tag 'Change Size', class:'button' %>
        <% end %>
        
    </div>

    <div class="rover_input">
    
    <%# By default there is one rover %>
        <%= form_tag(rovers_instructions_path, method: :get, remote: true) do %>
            <label>Set starting point :</label> 
            <%= hidden_field_tag :rover_id0,"", value:0 %>
            <%= text_field_tag :path0, params[:path0], autocomplete: 'off' %>
            <label>Give directions :</label> <%= text_field_tag :directions0, params[:directions0], autocomplete: 'off' %>
            <div class="rover_instructions"></div>
            <%= submit_tag 'Start Moving Rover', class:'start_btn button' %>
        <% end %>
    <%# Creates a new rover %>
    <%= button_to 'Generate a rover <- Click me!', create_rover_path, method: :get, remote: true, class:'create_rover button' %>
        
    </div>
</div>

    <div class="plateau_panel">
        <%# This builds the grid layout with the X,Y axis %>
        <% @grid_hash.reverse.each_with_index do |grid, index| %>
            <div class="location">
                <p>X(<%= grid.split("_")[0] %>) , Y(<%= grid.split("_")[1] %>)</p>
                <div id="<%= "#{grid.split("_")[0]}_#{grid.split("_")[1]}" %>">
                
                </div>
            </div>
        <% end %>
    </div>

    <div id="log">
    <b>Rover Action Logs:</b>
    </div>


    <script>
    var grid = <%= raw @grid_hash.to_json %>
    </script>